### PR TITLE
🔒 Update dependencies for `npm-audit` failures

### PR DESCRIPTION
**Pull request by grdryn**
Without these changes, `npm install` doesn't work without extra
flags. See below for the output of `npm audit`. The changes in this
commit were done by `npm audit fix`.

```
npm audit

                       === npm audit security report ===

┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Missing Origin Validation                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ webpack-dev-server                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ react-scripts                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ react-scripts > webpack-dev-server                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/725                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ underscore.string                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ react-markdown                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ react-markdown > html-to-react > underscore.string.fp >      │
│               │ underscore.string                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/745                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

found 2 vulnerabilities (1 moderate, 1 high) in 58477 scanned packages
  run `npm audit fix` to fix 2 of them.
```

### CODE REVIEW

**Comment by grdryn** [comment]
I don't know what needs to happen to get the CircleCI builds to trigger...is it manual or something?

**Comment by grdryn** [comment]
@wei-lee Hmm, is that what's causing the jobs to not get triggered? Why won't it trigger for PRs from forks? It seems like an unnecessary barrier for contributors who aren't already part of the org or who haven't got the required access to create branches on the origin repo. :confused:

**Comment by wei-lee** [comment]
@grdryn yeah, it is a limitation of how we setup the circle ci job. To use some of the third-party services (like coverall, and dockerhub), we use secure environment variables in Circle ci to store the access keys to those services. For security reasons, we can't support build from fork as it will leak the value of the keys to anyone who creates a PR. So for now, we don't support build from fork. But we will come back to fix this once there are other contributors.

**Comment by grdryn** [comment]
Closing this in favour or #172.

**Pull request closed without merging**
