### PR TITLE
Renaming the project

### PR DESCRIPTION
**Pull request by secondsun**
As per my email, the project has been renamed.  These changes should cover everything (I'm still testing but I'm tossing out an early many eyes approach')

### CODE REVIEW

**Comment by secondsun** [comment]
@wei-lee I'll take a look.  Can you give me push access to the aerogear docker org?

**Comment by secondsun** [comment]
@secondsun I think it is failing because we renamed the repo and need to refresh our coveralls token.  I don't have permissions to do this.

**Comment by wei-lee** [comment]
@secondsun ok, I will get it fixed.

**Comment by wei-lee** [comment]
@secondsun fixed!

**Pull request merged**
